/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class QuanTriGUI extends javax.swing.JFrame {
    /**
     * Creates new form QuanTriGUI
     */
    public QuanTriGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        panelEmployeer = new javax.swing.JPanel();
        btnEmployeer = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelCustomer = new javax.swing.JPanel();
        btnCustomer = new javax.swing.JLabel();
        btnProduct = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnSupplier = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnStatistical = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(54, 48, 98));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setBackground(new java.awt.Color(54, 48, 98));
        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEmployeer.setBackground(new java.awt.Color(85, 65, 141));
        panelEmployeer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEmployeerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEmployeerMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelEmployeerMousePressed(evt);
            }
        });

        btnEmployeer.setBackground(new java.awt.Color(85, 65, 141));
        btnEmployeer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEmployeer.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeer.setText("Employeer");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/employeer.png"))); // NOI18N

        javax.swing.GroupLayout panelEmployeerLayout = new javax.swing.GroupLayout(panelEmployeer);
        panelEmployeer.setLayout(panelEmployeerLayout);
        panelEmployeerLayout.setHorizontalGroup(
            panelEmployeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEmployeerLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnEmployeer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelEmployeerLayout.setVerticalGroup(
            panelEmployeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEmployeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEmployeer, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidebar.add(panelEmployeer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 40));

        panelCustomer.setBackground(new java.awt.Color(64, 43, 100));
        panelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelCustomerMousePressed(evt);
            }
        });
        panelCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                panelCustomerKeyPressed(evt);
            }
        });

        btnCustomer.setBackground(new java.awt.Color(63, 43, 100));
        btnCustomer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCustomer.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomer.setText("Customer");

        javax.swing.GroupLayout panelCustomerLayout = new javax.swing.GroupLayout(panelCustomer);
        panelCustomer.setLayout(panelCustomerLayout);
        panelCustomerLayout.setHorizontalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCustomerLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(btnCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        panelCustomerLayout.setVerticalGroup(
            panelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        sidebar.add(panelCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 40));

        btnProduct.setBackground(new java.awt.Color(64, 43, 100));
        btnProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnProductMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Products");

        javax.swing.GroupLayout btnProductLayout = new javax.swing.GroupLayout(btnProduct);
        btnProduct.setLayout(btnProductLayout);
        btnProductLayout.setHorizontalGroup(
            btnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnProductLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        btnProductLayout.setVerticalGroup(
            btnProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(btnProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 228, 240, 40));

        btnSupplier.setBackground(new java.awt.Color(64, 43, 100));
        btnSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupplierMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Supplier");

        javax.swing.GroupLayout btnSupplierLayout = new javax.swing.GroupLayout(btnSupplier);
        btnSupplier.setLayout(btnSupplierLayout);
        btnSupplierLayout.setHorizontalGroup(
            btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSupplierLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        btnSupplierLayout.setVerticalGroup(
            btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(btnSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 268, 240, 40));

        btnStatistical.setBackground(new java.awt.Color(64, 43, 100));
        btnStatistical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStatisticalMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Statistical");

        javax.swing.GroupLayout btnStatisticalLayout = new javax.swing.GroupLayout(btnStatistical);
        btnStatistical.setLayout(btnStatisticalLayout);
        btnStatisticalLayout.setHorizontalGroup(
            btnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnStatisticalLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        btnStatisticalLayout.setVerticalGroup(
            btnStatisticalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        sidebar.add(btnStatistical, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/171104629891273425.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        sidebar.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 20, 130, 100));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STORE");
        sidebar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 90, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE");
        sidebar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 90, 30));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        sidebar.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 20));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelEmployeerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeerMouseClicked
        // TODO add your handling code here:
//        new testGUI().setVisible(true);
    }//GEN-LAST:event_panelEmployeerMouseClicked

    private void panelEmployeerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeerMousePressed
        // TODO add your handling code here:
        setColor(panelEmployeer);
        resetColor(btnProduct);
        resetColor(btnStatistical);
        resetColor(btnSupplier);
        resetColor(panelCustomer);
    }//GEN-LAST:event_panelEmployeerMousePressed

    private void panelEmployeerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeerMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panelEmployeerMouseEntered

    private void panelCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_panelCustomerKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_panelCustomerKeyPressed

    private void btnProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductMousePressed
        // TODO add your handling code here:
        setColor(btnProduct);
        resetColor(panelCustomer);
        resetColor(panelEmployeer);
        resetColor(btnStatistical);
        resetColor(btnSupplier);
    }//GEN-LAST:event_btnProductMousePressed

    private void btnSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMousePressed
        // TODO add your handling code here:
        setColor(btnSupplier);
        resetColor(btnProduct);
        resetColor(panelCustomer);
        resetColor(panelEmployeer);
        resetColor(btnStatistical);
    }//GEN-LAST:event_btnSupplierMousePressed

    private void btnStatisticalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatisticalMousePressed
        // TODO add your handling code here:
        setColor(btnStatistical);
        resetColor(btnSupplier);
        resetColor(btnProduct);
        resetColor(panelCustomer);
        resetColor(panelEmployeer);
    }//GEN-LAST:event_btnStatisticalMousePressed

    private void panelCustomerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelCustomerMousePressed
        // TODO add your handling code here:
        setColor(panelCustomer);
        resetColor(panelEmployeer);
        resetColor(btnProduct);
        resetColor(btnStatistical);
        resetColor(btnSupplier);
    }//GEN-LAST:event_panelCustomerMousePressed

    private void setColor(JPanel panel) {
        panel.setBackground(new Color(85,65,141));
    }
    private void resetColor(JPanel panel) {
        panel.setBackground(new Color(64,43,100));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanTriGUI().setVisible(true);
            }
        });
    }

    public void openQuanTriGUI() {
        JFrame frame = new JFrame("Quan tri");
        setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel btnCustomer;
    private javax.swing.JLabel btnEmployeer;
    private javax.swing.JPanel btnProduct;
    private javax.swing.JPanel btnStatistical;
    private javax.swing.JPanel btnSupplier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelCustomer;
    private javax.swing.JPanel panelEmployeer;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
