/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class QuanTriGUI extends javax.swing.JFrame {
    /**
     * Creates new form QuanTriGUI
     */
    private String IDNhanVien;
    private String LoaiNhanVien;
    
    public QuanTriGUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public void setUserValueFromLoginGUI(String IDNhanVien, String LoaiNhanVien) {
        this.IDNhanVien = IDNhanVien;
        this.LoaiNhanVien = LoaiNhanVien;
        txtMaNV.setText(IDNhanVien);
        txtLoaiNhanVien.setText(LoaiNhanVien);
        if (LoaiNhanVien.equals("Nhân viên")) {
            openNhanVienGUI.setEnabled(false);
            openSanPhamGUI.setEnabled(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound1 = new StorageGUI.PanelRound();
        txtMaNV = new javax.swing.JLabel();
        txtLoaiNhanVien = new javax.swing.JLabel();
        btnSuaThongTin = new StorageGUI.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        btnDangXuat = new StorageGUI.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        openBanHangGUI = new StorageGUI.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        openHoaDonGUI = new StorageGUI.PanelRound();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        openKhuyenMaiGUI = new StorageGUI.PanelRound();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        openSanPhamGUI = new StorageGUI.PanelRound();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        openNhanVienGUI = new StorageGUI.PanelRound();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        openKhachHangGUI = new StorageGUI.PanelRound();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        panelRound11 = new StorageGUI.PanelRound();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panelRound12 = new StorageGUI.PanelRound();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(54, 48, 98));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/171104629891273425.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("PHONE");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STORE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        sidebar.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 150));

        panelRound1.setBackground(new java.awt.Color(255, 255, 255));
        panelRound1.setRoundBottomLeft(10);
        panelRound1.setRoundBottomRight(10);
        panelRound1.setRoundTopLeft(10);
        panelRound1.setRoundTopRight(10);

        txtMaNV.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        txtMaNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMaNV.setText("NV001");

        txtLoaiNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLoaiNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtLoaiNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtLoaiNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(txtMaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoaiNhanVien)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        sidebar.add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 170, 70));

        btnSuaThongTin.setBackground(new java.awt.Color(255, 255, 255));
        btnSuaThongTin.setRoundBottomLeft(10);
        btnSuaThongTin.setRoundBottomRight(10);
        btnSuaThongTin.setRoundTopLeft(10);
        btnSuaThongTin.setRoundTopRight(10);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SỬA THÔNG TIN");

        javax.swing.GroupLayout btnSuaThongTinLayout = new javax.swing.GroupLayout(btnSuaThongTin);
        btnSuaThongTin.setLayout(btnSuaThongTinLayout);
        btnSuaThongTinLayout.setHorizontalGroup(
            btnSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        btnSuaThongTinLayout.setVerticalGroup(
            btnSuaThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSuaThongTinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(btnSuaThongTin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, 30));

        btnDangXuat.setBackground(new java.awt.Color(255, 255, 255));
        btnDangXuat.setRoundBottomLeft(10);
        btnDangXuat.setRoundBottomRight(10);
        btnDangXuat.setRoundTopLeft(10);
        btnDangXuat.setRoundTopRight(10);
        btnDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDangXuatMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("ĐĂNG XUẤT");

        javax.swing.GroupLayout btnDangXuatLayout = new javax.swing.GroupLayout(btnDangXuat);
        btnDangXuat.setLayout(btnDangXuatLayout);
        btnDangXuatLayout.setHorizontalGroup(
            btnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        btnDangXuatLayout.setVerticalGroup(
            btnDangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, 30));

        openBanHangGUI.setBackground(new java.awt.Color(255, 255, 255));
        openBanHangGUI.setRoundBottomLeft(20);
        openBanHangGUI.setRoundBottomRight(20);
        openBanHangGUI.setRoundTopLeft(20);
        openBanHangGUI.setRoundTopRight(20);
        openBanHangGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openBanHangGUIMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BÁN HÀNG");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/store.png"))); // NOI18N

        javax.swing.GroupLayout openBanHangGUILayout = new javax.swing.GroupLayout(openBanHangGUI);
        openBanHangGUI.setLayout(openBanHangGUILayout);
        openBanHangGUILayout.setHorizontalGroup(
            openBanHangGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(openBanHangGUILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel9)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        openBanHangGUILayout.setVerticalGroup(
            openBanHangGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openBanHangGUILayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        sidebar.add(openBanHangGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        openHoaDonGUI.setBackground(new java.awt.Color(255, 255, 255));
        openHoaDonGUI.setRoundBottomLeft(20);
        openHoaDonGUI.setRoundBottomRight(20);
        openHoaDonGUI.setRoundTopLeft(20);
        openHoaDonGUI.setRoundTopRight(20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HÓA ĐƠN");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/bill.png"))); // NOI18N

        javax.swing.GroupLayout openHoaDonGUILayout = new javax.swing.GroupLayout(openHoaDonGUI);
        openHoaDonGUI.setLayout(openHoaDonGUILayout);
        openHoaDonGUILayout.setHorizontalGroup(
            openHoaDonGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(openHoaDonGUILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel11)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        openHoaDonGUILayout.setVerticalGroup(
            openHoaDonGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openHoaDonGUILayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(14, 14, 14))
        );

        sidebar.add(openHoaDonGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        openKhuyenMaiGUI.setBackground(new java.awt.Color(255, 255, 255));
        openKhuyenMaiGUI.setRoundBottomLeft(20);
        openKhuyenMaiGUI.setRoundBottomRight(20);
        openKhuyenMaiGUI.setRoundTopLeft(20);
        openKhuyenMaiGUI.setRoundTopRight(20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("KHUYẾN MÃI");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/sale.png"))); // NOI18N

        javax.swing.GroupLayout openKhuyenMaiGUILayout = new javax.swing.GroupLayout(openKhuyenMaiGUI);
        openKhuyenMaiGUI.setLayout(openKhuyenMaiGUILayout);
        openKhuyenMaiGUILayout.setHorizontalGroup(
            openKhuyenMaiGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(openKhuyenMaiGUILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openKhuyenMaiGUILayout.setVerticalGroup(
            openKhuyenMaiGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openKhuyenMaiGUILayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(14, 14, 14))
        );

        sidebar.add(openKhuyenMaiGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 170, -1));

        openSanPhamGUI.setBackground(new java.awt.Color(255, 255, 255));
        openSanPhamGUI.setRoundBottomLeft(20);
        openSanPhamGUI.setRoundBottomRight(20);
        openSanPhamGUI.setRoundTopLeft(20);
        openSanPhamGUI.setRoundTopRight(20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("SẢN PHẨM");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/product.png"))); // NOI18N

        javax.swing.GroupLayout openSanPhamGUILayout = new javax.swing.GroupLayout(openSanPhamGUI);
        openSanPhamGUI.setLayout(openSanPhamGUILayout);
        openSanPhamGUILayout.setHorizontalGroup(
            openSanPhamGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(openSanPhamGUILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel15)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        openSanPhamGUILayout.setVerticalGroup(
            openSanPhamGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openSanPhamGUILayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(14, 14, 14))
        );

        sidebar.add(openSanPhamGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 170, -1));

        openNhanVienGUI.setBackground(new java.awt.Color(255, 255, 255));
        openNhanVienGUI.setRoundBottomLeft(20);
        openNhanVienGUI.setRoundBottomRight(20);
        openNhanVienGUI.setRoundTopLeft(20);
        openNhanVienGUI.setRoundTopRight(20);
        openNhanVienGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openNhanVienGUIMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("NHÂN VIÊN");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/staff.png"))); // NOI18N

        javax.swing.GroupLayout openNhanVienGUILayout = new javax.swing.GroupLayout(openNhanVienGUI);
        openNhanVienGUI.setLayout(openNhanVienGUILayout);
        openNhanVienGUILayout.setHorizontalGroup(
            openNhanVienGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(openNhanVienGUILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel17)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        openNhanVienGUILayout.setVerticalGroup(
            openNhanVienGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openNhanVienGUILayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(14, 14, 14))
        );

        sidebar.add(openNhanVienGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 170, -1));

        openKhachHangGUI.setBackground(new java.awt.Color(255, 255, 255));
        openKhachHangGUI.setRoundBottomLeft(20);
        openKhachHangGUI.setRoundBottomRight(20);
        openKhachHangGUI.setRoundTopLeft(20);
        openKhachHangGUI.setRoundTopRight(20);
        openKhachHangGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openKhachHangGUIMouseClicked(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("KHÁCH HÀNG");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/customer.png"))); // NOI18N

        javax.swing.GroupLayout openKhachHangGUILayout = new javax.swing.GroupLayout(openKhachHangGUI);
        openKhachHangGUI.setLayout(openKhachHangGUILayout);
        openKhachHangGUILayout.setHorizontalGroup(
            openKhachHangGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
            .addGroup(openKhachHangGUILayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        openKhachHangGUILayout.setVerticalGroup(
            openKhachHangGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, openKhachHangGUILayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(14, 14, 14))
        );

        sidebar.add(openKhachHangGUI, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 170, -1));

        panelRound11.setBackground(new java.awt.Color(255, 255, 255));
        panelRound11.setRoundBottomLeft(20);
        panelRound11.setRoundBottomRight(20);
        panelRound11.setRoundTopLeft(20);
        panelRound11.setRoundTopRight(20);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("NHẬP HÀNG");

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/store.png"))); // NOI18N

        javax.swing.GroupLayout panelRound11Layout = new javax.swing.GroupLayout(panelRound11);
        panelRound11.setLayout(panelRound11Layout);
        panelRound11Layout.setHorizontalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound11Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel21)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelRound11Layout.setVerticalGroup(
            panelRound11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound11Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(14, 14, 14))
        );

        sidebar.add(panelRound11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 170, -1));

        panelRound12.setBackground(new java.awt.Color(255, 255, 255));
        panelRound12.setRoundBottomLeft(20);
        panelRound12.setRoundBottomRight(20);
        panelRound12.setRoundTopLeft(20);
        panelRound12.setRoundTopRight(20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("THỐNG KÊ");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/image/store.png"))); // NOI18N

        javax.swing.GroupLayout panelRound12Layout = new javax.swing.GroupLayout(panelRound12);
        panelRound12.setLayout(panelRound12Layout);
        panelRound12Layout.setHorizontalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRound12Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel23)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        panelRound12Layout.setVerticalGroup(
            panelRound12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(14, 14, 14))
        );

        sidebar.add(panelRound12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 170, -1));

        background.add(sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 710));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBanHangGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openBanHangGUIMouseClicked
        // TODO add your handling code here:
        BanHangGUI banHangGUI = new BanHangGUI();
        banHangGUI.setUserValueFromLoginGUI(IDNhanVien, LoaiNhanVien);
        this.dispose();
    }//GEN-LAST:event_openBanHangGUIMouseClicked

    private void openNhanVienGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openNhanVienGUIMouseClicked
        // TODO add your handling code here:
        NhanVienGUI nhanVienGUI = new NhanVienGUI();
        nhanVienGUI.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_openNhanVienGUIMouseClicked

    private void openKhachHangGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openKhachHangGUIMouseClicked
        // TODO add your handling code here:
        KhachHangGUI khachHangGUI = new KhachHangGUI();
        khachHangGUI.setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_openKhachHangGUIMouseClicked

    private void btnDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDangXuatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanTriGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanTriGUI().setVisible(true);
            }
        });
    }

    public void openQuanTriGUI() {
        JFrame frame = new JFrame("Quan tri");
        setLocationRelativeTo(null);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private StorageGUI.PanelRound btnDangXuat;
    private StorageGUI.PanelRound btnSuaThongTin;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private StorageGUI.PanelRound openBanHangGUI;
    private StorageGUI.PanelRound openHoaDonGUI;
    private StorageGUI.PanelRound openKhachHangGUI;
    private StorageGUI.PanelRound openKhuyenMaiGUI;
    private StorageGUI.PanelRound openNhanVienGUI;
    private StorageGUI.PanelRound openSanPhamGUI;
    private StorageGUI.PanelRound panelRound1;
    private StorageGUI.PanelRound panelRound11;
    private StorageGUI.PanelRound panelRound12;
    private javax.swing.JPanel sidebar;
    private javax.swing.JLabel txtLoaiNhanVien;
    private javax.swing.JLabel txtMaNV;
    // End of variables declaration//GEN-END:variables
}
