package GUI;

import BUS.ChiTietChuongTrinhGiamGiaBUS;
import BUS.ChuongTrinhGiamGiaBUS;
import BUS.SanPhamBUS;
import DTO.ChiTietChuongTrinhGiamGiaDTO;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ThemSPGG extends javax.swing.JFrame {

    private ChiTietChuongTrinhGiamGiaBUS chiTietChuongTrinhGiamGiaBUS;
    private ChuongTrinhGiamGiaBUS ctggBUS;
    private SanPhamBUS sanPhamBUS;
    private DefaultTableModel modelGiamGia;
    private String IDGiamGia;

    public ThemSPGG() {
    }

    public ThemSPGG(String IDGiamGia) {
        initComponents();
        setLocationRelativeTo(null);

        this.IDGiamGia = IDGiamGia;
        modelGiamGia = (DefaultTableModel) tblGiamGia.getModel();
        tblGiamGia.fixTable(jScrollPane1);

        chiTietChuongTrinhGiamGiaBUS = new ChiTietChuongTrinhGiamGiaBUS();
        ctggBUS = new ChuongTrinhGiamGiaBUS();

        renderTableGiamGia();
        renderComboBoxMaSanPham();
    }

    public void setIDGiamGia(String IDGiamGia) {
        this.IDGiamGia = IDGiamGia;
    }

    public void renderComboBoxMaSanPham() {
        jComboBox1.removeAllItems();
        ArrayList<ChiTietChuongTrinhGiamGiaDTO> danhSachChiTietCTGG = chiTietChuongTrinhGiamGiaBUS.getDanhSachChiTietCTGG();
        ArrayList<String> arrayMaSP = chiTietChuongTrinhGiamGiaBUS.getArrayIDSanPhamFromSanPhamBUS();
        ArrayList<String> tmpArrayMaSP = new ArrayList<>();
        for (ChiTietChuongTrinhGiamGiaDTO chiTietChuongTrinhGiamGiaDTO : danhSachChiTietCTGG) {
            if (chiTietChuongTrinhGiamGiaDTO.getIDGiamGia().equals(IDGiamGia)) {
                tmpArrayMaSP.add(chiTietChuongTrinhGiamGiaDTO.getIDSanPham());
            }
        }

        for (String maSP : arrayMaSP) {
            if (!tmpArrayMaSP.contains(maSP)) {
                jComboBox1.addItem(maSP);
            }
        }

    }

    public void renderTableGiamGia() {
        ArrayList<ChiTietChuongTrinhGiamGiaDTO> danhSachChiTietCTGG = chiTietChuongTrinhGiamGiaBUS.getDanhSachChiTietCTGG();
        modelGiamGia.setRowCount(0);
        for (ChiTietChuongTrinhGiamGiaDTO ctctgg : danhSachChiTietCTGG) {
            if (ctctgg.getIDGiamGia().equals(IDGiamGia)) {
                modelGiamGia.addRow(new Object[]{ctctgg.getIDSanPham(), ctctgg.getPhanTramGiamGia() + "%"});
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGiamGia = new StorageGUI.TableDarkGUI();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPhanTramGG = new StorageGUI.TextField();
        btnThem = new StorageGUI.Button();
        btnXoa = new StorageGUI.Button();
        btnSua = new StorageGUI.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(54, 48, 98));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM SẢN PHẨM GIẢM GIÁ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        tblGiamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã sản phẩm", "Phần trăm giảm giá"
            }
        ));
        tblGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiamGiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGiamGia);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã sản phẩm:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Phần trăm giảm:");

        btnThem.setText("THÊM");
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXoaMouseClicked(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhanTramGG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhanTramGG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        String IDSanPham = (String) jComboBox1.getSelectedItem();
        if (txtPhanTramGG.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Vui lòng nhập phần trăm giảm giá", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        double PhanTramGG = Double.parseDouble(txtPhanTramGG.getText());
        
        if (PhanTramGG == 0 || PhanTramGG >= 100) {
            JOptionPane.showMessageDialog(null, "Phần trăm giảm giá không hợp lệ", "Lỗi", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        ChiTietChuongTrinhGiamGiaDTO chiTietChuongTrinhGiamGiaDTO = new ChiTietChuongTrinhGiamGiaDTO(IDGiamGia, IDSanPham, PhanTramGG);
        
        if (chiTietChuongTrinhGiamGiaBUS.addChiTietGG(chiTietChuongTrinhGiamGiaDTO)) {
            JOptionPane.showMessageDialog(null, "THÊM THÀNH CÔNG");
            renderComboBoxMaSanPham();
            renderTableGiamGia();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblGiamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGiamGiaMouseClicked
        int i = tblGiamGia.getSelectedRow();
        txtPhanTramGG.setText(modelGiamGia.getValueAt(i, 1).toString());
    }//GEN-LAST:event_tblGiamGiaMouseClicked

    private void btnXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseClicked
        // TODO add your handling code here:
        int i = tblGiamGia.getSelectedRow();
        String IDSanPham = modelGiamGia.getValueAt(i, 0).toString();
        
        if (chiTietChuongTrinhGiamGiaBUS.deleteChiTietGG(IDGiamGia, IDSanPham)) {
            JOptionPane.showMessageDialog(null, "XÓA THÀNH CÔNG");
        }
        
        renderTableGiamGia();
        renderComboBoxMaSanPham();
    }//GEN-LAST:event_btnXoaMouseClicked

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
        int i = tblGiamGia.getSelectedRow();
        String IDSanPham = modelGiamGia.getValueAt(i, 0).toString();
        double PhanTramGG = Double.parseDouble(txtPhanTramGG.getText());
        
        ChiTietChuongTrinhGiamGiaDTO chiTietChuongTrinhGiamGiaDTO = new ChiTietChuongTrinhGiamGiaDTO(IDGiamGia, IDSanPham, PhanTramGG);
        if (chiTietChuongTrinhGiamGiaBUS.updateChiTietGG(chiTietChuongTrinhGiamGiaDTO)) {
            JOptionPane.showMessageDialog(null, "SỬA THÀNH CÔNG");
        } 
        renderTableGiamGia();
        renderComboBoxMaSanPham();
    }//GEN-LAST:event_btnSuaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSPGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSPGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSPGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSPGG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSPGG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private StorageGUI.Button btnSua;
    private StorageGUI.Button btnThem;
    private StorageGUI.Button btnXoa;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private StorageGUI.TableDarkGUI tblGiamGia;
    private StorageGUI.TextField txtPhanTramGG;
    // End of variables declaration//GEN-END:variables

}
